/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FundProject__factory } from "./FundProject__factory";
export { Project__factory } from "./Project__factory";
